### ISSUE TITLE
qt.qpa.xcb: could not connect to display $IP:0

### ISSUE THREAD

**Issue by kaka-lin** [jozo/docker-pyqt5#5]
Hi, 

When I use it on macOS as the below method, I got the error: `qt.qpa.xcb: could not connect to display $IP:0`

```bash
IP=$(ifconfig en0 | grep inet | awk '$1=="inet" {print $2}')
xhost +
```
```
docker run --rm -it \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e DISPLAY=$IP:0 \
    -u qtuser \
    jozo/pyqt5 python3 /tmp/hello.py
```

**Comment by kaka-lin** [comment]
I solved !

**Comment by jozo** [comment]
@kaka-lin can you please share your solution? I guess the problem was that XQuartz was not running.

**Comment by kaka-lin** [comment]
@jozo I used `host.docker.internal:0` instead of `$IP:0`

This is my repo: https://github.com/kaka-lin/qt-template/tree/master/docker

**Comment by kaka-lin** [comment]
@jozo  I used host.docker.internal:0 instead of `$IP:0`

This is my repo: https://github.com/kaka-lin/qt-template/tree/master/docker
