### ISSUE TITLE
Docker Error: image with reference jozo/pyqt5 was found but does not match the specified platform: wanted linux/arm/v7, actual: linux/amd64

### ISSUE THREAD

**Issue by kennedyjosh** [jozo/docker-pyqt5#6]
Hello,

I am trying to use this on a Raspberry Pi 4 running Raspbian, and when I try to run the test script using:
```
docker run --rm -it \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e DISPLAY=$DISPLAY \
    -u qtuser \
    jozo/pyqt5 python3 /tmp/hello.py
```
I get the following error:
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
standard_init_linux.go:219: exec user process caused: exec format error
```

Do you know how I might fix this issue? Thanks

**Comment by jozo** [comment]
You need to use base image which is compatible with Raspberry Pi. You mentioned Raspbian - try to use that as base image and then add steps from Dockerfile in this repo. https://github.com/jozo/docker-pyqt5/blob/master/default/Dockerfile

I don't have Raspberry Pi to test this, so you have to figure it out yourself.
